### PR TITLE
Better support for emoji with zero width connectors

### LINKED ISSUE #12: FindAll method returns wrong results for some emojis (e.g. 👨‍👩‍👦‍👦))
스크린샷 2021-02-19 오전 10 22 46

For this, findAll method detects two emojis and it happens for other emojis with 2 sons. 

스크린샷 2021-02-19 오전 10 22 59

### PR DESCRIPTION
**Pull request by tmdvs**
The [zero-width connector](https://emojipedia.org/zero-width-joiner#technical) is a special character used to combine multiple emoji into a single emoji character on screen. For example 👩‍👩‍👧‍👧

This patches the code to skip specific instances of the zero-width connector to avoid parsing parts of the emoji as unicode characters/breaking into multiple emoji.

This is based on https://github.com/tmdvs/Go-Emoji-Utils/issues/12#issuecomment-1362747872

### CODE REVIEW

File: search.go [hunk 1]
```diff
@@ -9,7 +9,7 @@ import (
 
 // SearchResult - Occurrence of an emoji in a string
 type SearchResult struct {
-	Match       interface{}
```
Comment (tmdvs) [inline search.go:12]: This should have never been an interface, it leads to unnecessary type conversion/checking.
